version: '3.1'

tgbot:
  container_name: bot
  build:
    context: .
  command: python app.python
  restart: always
  networks:
    - botnet
  env_file:
    - ".env"

networks:
  botnet:
    driver: bridge
