version: '3.3'

services:
  bot:
    image: "debts_bot_test"
    container_name: "Debts_bot_test"
    build:
      context: .
    volumes:
      - .:/src/Debts_bot_test
    command: nohup python3 app.py &
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge
