version: '3.3'

services:
  bot:
    image: debs_bot
    container_name: Debs_bot
    build:
      context: .
    working_dir: /src/Debs_bot
    volumes:
      - .:/src/Debs_bot
    command: python app.py
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge
