version: '3.3'

services:
  bot:
    image: debts_bot
    container_name: Debts_bot
    build:
      context: .
    working_dir: /src/Debts_bot
    volumes:
      - .:/src/Debts_bot
    command: nohup python3 app.py &
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge
